import React from "react";
import styles from "./styles.module.css";
import Breadcrumbs from "@/components/Breadcrumbs";

const Privacy = () => {
  return (
    <React.Fragment>
      <div className={styles.privacy}>
        <div className={styles.container}>
          <Breadcrumbs path={""} />
          <div className={styles.privacyWrapper}>
            <h2>PRIVACY POLICY</h2>
            <div>
              <h3>Introduction</h3>
              <p>
                Welcome to Flush John. Flush John (“us”, “we”, or “our”)
                operates flushjohn.com (hereinafter referred to as “Service”).
                Our Privacy Policy governs your visit to flushjohn.com, and
                explains how we collect, safeguard and disclose information that
                results from your use of our Service. We use your data to
                provide and improve Service. By using Service, you agree to the
                collection and use of information in accordance with this
                policy. Unless otherwise defined in this Privacy Policy, the
                terms used in this Privacy Policy have the same meanings as in
                our Terms and Conditions. Our Terms and Conditions (“Terms”)
                govern all use of our Service and together with the Privacy
                Policy constitutes your agreement with us (“agreement”).
              </p>
            </div>
            <div>
              <h3>Definitions</h3>
              <ul>
                <li>
                  SERVICE means the flushjohn.com website operated by Flush
                  John.
                </li>
                <li>
                  PERSONAL DATA means data about a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </li>
                <li>
                  USAGE DATA is data collected automatically either generated by
                  the use of Service or from Service infrastructure itself (for
                  example, the duration of a page visit).
                </li>
                <li>
                  COOKIES are small files stored on your device (computer or
                  mobile device).
                </li>
                <li>
                  DATA CONTROLLER means a natural or legal person who (either
                  alone or jointly or in common with other persons) determines
                  the purposes for which and the manner in which any personal
                  data are, or are to be, processed. For the purpose of this
                  Privacy Policy, we are a Data Controller of your data.
                </li>
                <li>
                  DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or
                  legal person who processes the data on behalf of the Data
                  Controller. We may use the services of various Service
                  Providers in order to process your data more effectively.
                </li>
                <li>
                  DATA SUBJECT is any living individual who is the subject of
                  Personal Data.
                </li>
                <li>
                  THE USER is the individual using our Service. The User
                  corresponds to the Data Subject, who is the subject of
                  Personal Data.
                </li>
              </ul>
            </div>

            <div>
              <h3>Information Collection and Use</h3>
              <p>
                We collect several different types of information for various
                purposes to provide and improve our Service to you. Below are
                the types of data that we collect.
              </p>
              <ul>
                <li>
                  <h4>Personal Data</h4>
                  <p>
                    While using our Service, we may ask you to provide us with
                    certain personally identifiable information that can be used
                    to contact or identify you (“Personal Data”). Personally
                    identifiable information may include, but is not limited to:
                  </p>
                  <ul>
                    <li>First name and last name</li>
                    <li>Email address</li>
                    <li>Phone number</li>
                    <li>
                      Address, Country, State, Province, ZIP/Postal code, City
                    </li>
                    <li>Cookies and Usage Data</li>
                  </ul>
                  <p>
                    We may use your Personal Data to contact you with
                    newsletters, marketing or promotional materials and other
                    information that may be of interest to you. You may opt out
                    of receiving any, or all, of these communications from us by
                    following the unsubscribe link.
                  </p>
                </li>

                <li>
                  <h4>Usage Data</h4>
                  <p>
                    We may also collect information that your browser sends
                    whenever you visit our Service or when you access Service by
                    or through any device (“Usage Data”).
                  </p>
                  <p>
                    This Usage Data may include information such as your
                    computer’s Internet Protocol address (e.g. IP address),
                    browser type, browser version, the pages of our Service that
                    you visit, the time and date of your visit, the time spent
                    on those pages, unique device identifiers and other
                    diagnostic data.
                  </p>
                  <p>
                    When you access Service with a device, this Usage Data may
                    include information such as the type of device you use, your
                    device unique ID, the IP address of your device, your device
                    operating system, the type of Internet browser you use,
                    unique device identifiers and other diagnostic data.
                  </p>
                </li>

                <li>
                  <h4>Tracking Cookies Data</h4>
                  <p>
                    We use cookies and similar tracking technologies to track
                    the activity on our Service and we hold certain information.
                  </p>
                  <p>
                    Cookies are files with a small amount of data which may
                    include an anonymous unique identifier. Cookies are sent to
                    your browser from a website and stored on your device. Other
                    tracking technologies are also used such as beacons, tags
                    and scripts to collect and track information and to improve
                    and analyze our Service.
                  </p>
                  <p>
                    You can instruct your browser to refuse all cookies or to
                    indicate when a cookie is being sent. However, if you do not
                    accept cookies, you may not be able to use some portions of
                    our Service.
                  </p>
                  <p>Examples of Cookies we use:</p>
                  <ul>
                    <li>
                      Session Cookies: We use Session Cookies to operate our
                      Service.
                    </li>
                    <li>
                      Preference Cookies: We use Preference Cookies to remember
                      your preferences and various settings.
                    </li>
                    <li>
                      Security Cookies: We use Security Cookies for security
                      purposes.
                    </li>
                    <li>
                      Advertising Cookies: Advertising Cookies are used to serve
                      you with advertisements that may be relevant to you and
                      your interests.
                    </li>
                  </ul>
                </li>
              </ul>

              <div>
                <h3>Use of Data</h3>
                <h4>We use the collected data for various purposes:</h4>
                <ul>
                  <li>to provide and maintain our Service;</li>
                  <li>
                    to allow you to participate in interactive features of our
                    Service when you choose to do so;
                  </li>
                  <li>to provide customer support;</li>
                  <li>
                    to gather analysis or valuable information so that we can
                    improve our Service;
                  </li>
                  <li>to monitor the usage of our Service;</li>
                  <li>to detect, prevent and address technical issues;</li>
                  <li>to fulfil any other purpose for which you provide it;</li>
                  <li>to notify you about changes to our Service;</li>
                  <li>
                    to carry out our obligations and enforce our rights arising
                    from any contracts entered into between you and us,
                    including for billing and collection;
                  </li>
                  <li>
                    to provide you with notices about your account and/or
                    subscription, including expiration and renewal notices,
                    email-instructions, etc.;
                  </li>
                  <li>
                    to provide you with news, special offers and general
                    information about other goods, services and events which we
                    offer that are similar to those that you have already
                    purchased or enquired about unless you have opted not to
                    receive such information;
                  </li>
                  <li>
                    in any other way we may describe when you provide the
                    information;
                  </li>
                  <li>for any other purpose with your consent.</li>
                </ul>
              </div>

              <div>
                <h3>Retention of Data</h3>
                <p>
                  We will retain your Personal Data only for as long as is
                  necessary for the purposes set out in this Privacy Policy. We
                  will retain and use your Personal Data to the extent necessary
                  to comply with our legal obligations (for example, if we are
                  required to retain your data to comply with applicable laws),
                  resolve disputes, and enforce our legal agreements and
                  policies.
                </p>
                <p>
                  We will also retain Usage Data for internal analysis purposes.
                  Usage Data is generally retained for a shorter period, except
                  when this data is used to strengthen the security or to
                  improve the functionality of our Service, or we are legally
                  obligated to retain this data for longer time periods.
                </p>
              </div>

              <div>
                <h3>Transfer of Data</h3>
                <p>
                  Your information, including Personal Data, may be transferred
                  to – and maintained on – computers located outside of your
                  state, province, country or other governmental jurisdiction
                  where the data protection laws may differ from those of your
                  jurisdiction.
                </p>
                <p>
                  If you are located outside United States and choose to provide
                  information to us, please note that we transfer the data,
                  including Personal Data, to United States and process it
                  there.
                </p>
                <p>
                  Your consent to this Privacy Policy followed by your
                  submission of such information represents your agreement to
                  that transfer.
                </p>
                <p>
                  Flush John will take all the steps reasonably necessary to
                  ensure that your data is treated securely and in accordance
                  with this Privacy Policy and no transfer of your Personal Data
                  will take place to an organisation or a country unless there
                  are adequate controls in place including the security of your
                  data and other personal information.
                </p>
              </div>

              <div>
                <h3>Disclosure of Data</h3>
                <p>
                  We may disclose personal information that we collect, or you
                  provide:
                </p>
                <ul>
                  <li>
                    <h4>Disclosure for Law Enforcement</h4>
                    <p>
                      Under certain circumstances, we may be required to
                      disclose your Personal Data if required to do so by law or
                      in response to valid requests by public authorities.
                    </p>
                  </li>
                  <li>
                    <h4>Business Transaction</h4>
                    <p>
                      If we or our subsidiaries are involved in a merger,
                      acquisition or asset sale, your Personal Data may be
                      transferred.
                    </p>
                  </li>
                  <li>
                    <h4>Other cases</h4>
                    <ul>
                      <li>to our subsidiaries and affiliates;</li>
                      <li>
                        to contractors, service providers, and other third
                        parties we use to support our business;
                      </li>
                      <li>to fulfill the purpose for which you provide it;</li>
                      <li>
                        for the purpose of including your company’s logo on our
                        website;
                      </li>
                      <li>
                        for any other purpose disclosed by us when you provide
                        the information;
                      </li>
                      <li>with your consent in any other cases;</li>
                      <li>
                        if we believe disclosure is necessary or appropriate to
                        protect the rights, property, or safety of the Company,
                        our customers, or others.
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>

              <div>
                <h3>Security of Data</h3>
                <ul>
                  <li>
                    The security of your data is important to us but remember
                    that no method of transmission over the Internet or method
                    of electronic storage is 100% secure. While we strive to use
                    commercially acceptable means to protect your Personal Data,
                    we cannot guarantee its absolute security.
                  </li>
                  <li>
                    Your Data Protection Rights Under General Data Protection
                    Regulation (GDPR)
                  </li>
                  <li>
                    If you are a resident of the European Union (EU) and
                    European Economic Area (EEA), you have certain data
                    protection rights, covered by GDPR.
                  </li>
                  <li>
                    We aim to take reasonable steps to allow you to correct,
                    amend, delete, or limit the use of your Personal Data.
                  </li>
                  <li>
                    If you wish to be informed what Personal Data we hold about
                    you and if you want it to be removed from our systems,
                    please visit our contact page on the website.
                  </li>
                  <li>
                    In certain circumstances, you have the following data
                    protection rights:
                  </li>
                  <li>
                    <ul>
                      <li>
                        the right to access, update or to delete the information
                        we have on you;
                      </li>
                      <li>
                        the right of rectification. You have the right to have
                        your information rectified if that information is
                        inaccurate or incomplete;
                      </li>
                      <li>
                        the right to object. You have the right to object to our
                        processing of your Personal Data;
                      </li>
                      <li>
                        the right of restriction. You have the right to request
                        that we restrict the processing of your personal
                        information;
                      </li>
                      <li>
                        the right to data portability. You have the right to be
                        provided with a copy of your Personal Data in a
                        structured, machine-readable and commonly used format;
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>

              <div>
                <h3>
                  Your Data Protection Rights under the California Privacy
                  Protection Act (CalOPPA)
                </h3>
                <p>
                  CalOPPA is the first state law in the nation to require
                  commercial websites and online services to post a privacy
                  policy. The law’s reach stretches well beyond California to
                  require a person or company in the United States (and
                  conceivable the world) that operates websites collecting
                  personally identifiable information from California consumers
                  to post a conspicuous privacy policy on its website stating
                  exactly the information being collected and those individuals
                  with whom it is being shared, and to comply with this policy.
                </p>
                <p>According to CalOPPA we agree to the following:</p>
                <ul>
                  <li>users can visit our site anonymously;</li>
                  <li>
                    our Privacy Policy link includes the word “Privacy”, and can
                    easily be found on the home page of our website;
                  </li>
                  <li>
                    users will be notified of any privacy policy changes on our
                    Privacy Policy Page;
                  </li>
                  <li>
                    users are able to change their personal information via
                    contact page on the website..
                  </li>
                </ul>
              </div>

              <div>
                <h3>Our Policy on “Do Not Track” Signals:</h3>
                <p>
                  We honor Do Not Track signals and do not track, plant cookies,
                  or use advertising when a Do Not Track browser mechanism is in
                  place. Do Not Track is a preference you can set in your web
                  browser to inform websites that you do not want to be tracked.
                </p>
                <p>
                  You can enable or disable Do Not Track by visiting the
                  Preferences or Settings page of your web browser.
                </p>
              </div>

              <div>
                <h3>Service Providers</h3>
                <p>
                  We may employ third party companies and individuals to
                  facilitate our Service (“Service Providers”), provide Service
                  on our behalf, perform Service-related services or assist us
                  in analysing how our Service is used.
                </p>
                <p>
                  These third parties have access to your Personal Data only to
                  perform these tasks on our behalf and are obligated not to
                  disclose or use it for any other purpose.
                </p>
              </div>

              <div>
                <h3>Analytics</h3>
                <p>
                  We may use third-party Service Providers to monitor and
                  analyze the use of our Service.
                </p>
              </div>

              <div>
                <h3>CI/CD tools</h3>
                <p>
                  We may use third-party Service Providers to automate the
                  development process of our Service.
                </p>
              </div>

              <div>
                <h3>Behavioral Remarketing</h3>
                <p>
                  We may use remarketing services to advertise on third party
                  websites to you after you visited our Service. We and our
                  third-party vendors use cookies to inform, optimise and serve
                  ads based on your past visits to our Service.
                </p>
                <p>
                  We may provide paid products and/or services within Service.
                  In that case, we use third-party services for payment
                  processing (e.g. payment processors).
                </p>
                <p>
                  We will not store or collect your payment card details. That
                  information is provided directly to our third-party payment
                  processors whose use of your personal information is governed
                  by their Privacy Policy. These payment processors adhere to
                  the standards set by PCI-DSS as managed by the PCI Security
                  Standards Council, which is a joint effort of brands like
                  Visa, Mastercard, American Express and Discover. PCI-DSS
                  requirements help ensure the secure handling of payment
                  information.
                </p>
              </div>

              <div>
                <h3>Links to Other Sites</h3>
                <p>
                  Our Service may contain links to other sites that are not
                  operated by us. If you click a third party link, you will be
                  directed to that third party’s site. We strongly advise you to
                  review the Privacy Policy of every site you visit.
                </p>
                <p>
                  We have no control over and assume no responsibility for the
                  content, privacy policies or practices of any third party
                  sites or services.
                </p>
              </div>

              <div>
                <h3>Changes to This Privacy Policy</h3>
                <p>We may update our Privacy Policy from time to time.</p>
                <p>
                  You are advised to review this Privacy Policy periodically for
                  any changes. Changes to this Privacy Policy are effective when
                  they are posted on this page.
                </p>
              </div>

              <div>
                <h3> Contact Us</h3>
                <p>
                  If you have any questions about this Privacy Policy, please
                  email us via our contact page on the website.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
};

export default Privacy;
