const homeData = {
  section1: {
    title:
      "We locally offer a wide range of portable toilet rentals and hand wash station rentals for all your events and job site needs.",
  },

  section2: {
    heading: "Our unique benefits and offerings",
    h1: "Prompt Quote & Bookings",
    h2: "Free & Quick Delivery",
    h3: "$15 Discount on Porta Potty Order.",
    h4: "Free Porta Potty Servicing",
    p1: "Our porta potty rentals are budget friendly and we provide a 15% discount on your 1st order.",
    p2: "We respect your time. Our professional customer support ensures instant quote and bookings.",
    p3: "Our experienced yard manager and driver facilitates seamless portable toilet delivery and pickup service with no any extra cost.",
    p4: "We provide weekly once cleaning service to our portable restrooms at no any extra cost. Also, we restock the porta potty unit with toilet papers.",
  },

  section3: {
    h1: "Events",
    h2: "Job Sites",
    h3: "Renovations",
    h4: "Disaster Relief",
    p1: "Our porta toilets are highly suitable for all your events like birthday parties, family reunions, weddings, etc.",
    p2: "We offer porta potty rental near you for all your job site needs, whether be a construction or any other long term use.",
    p3: "If you have a house renovation, hotel renovation or bathroom remodeling going on, you can always rely on us for your need of porta potties.",
    p4: "We are always ready to supply portable equipments like portable toilet and handwash stations in the areas those affected by the disasters.",
  },

  testimonialSection: {
    h1: "Terry Miles",
    h2: "Dean Lacey",
    h3: "Christine Barnes",
    h4: "Janet Estremera",
    p1: "The porta potty arrived on time as promised and it was wonderful. They are best porta potty rental service provider.",
    p2: "I had to rent a hand wash station when my house renovation was going on and the only company on which I could rely on was Reliable Portable. They are very quick in responding to your requirements and relatively cheaper in price.",
    p3: "Ordered an event portable toilet unit for a family reunion. The portable toilet arrived the next day of my order.",
    p4: "Portable toilet was pretty and nice. I had it ordered for a weeding event on a weekend. As promised over the phone, they dropped it off on Friday and picked up on Monday.",
  },

  sectionLocation: {
    title: "Our portable toilet service locations",
    list1: [
      "Alabama",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "District of Columbia",
      "Florida",
      "Georgia",
    ],
    list2: [
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
    ],
    list3: [
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
    ],
    list4: [
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
    ],
    list5: [
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
};

export const productData = {
  h1: "Standard Portable Restroom",
  h2: "Standard Portable Restroom",
  h3: "ADA-Compliant Portable Restroom",
  h4: "Flushable Restroom-Sink inside",
  h5: "Hand Washing Sink Station",
  h6: "Flushable Restroom-Sink inside",
  p1: "This is the most basic porta potty suited for events. It has a porta potty, urinal and toilet papers inside.",
  p2: "This a regular porta potty for job sites. It comes with toilet papers and a urinal inside.",
  p3: "The ADA toilets are larger in size than the regular restrooms and has wheel chair accessibility.",
  p4: "The flushable portable toilets for events has a flush and a sink. It is self-contained unit.",
  p5: "The standalone sink stations are self-contained and comes with soap and paper towels.",
  p6: "The flushable porta potties are self contained. It has a flush and a sink attached to it from inside.",
};

export const slideShowData = {
  ESPR: "sps_#EF648A.svg",
  EDFR: "flushable.svg",
  EACR: "ada_blue.svg",
  EHWS: "sink.svg",
  CSPR: "sps_blue.svg",
  CDFR: "VIP-Flush-1.svg",
  CACR: "ada_blue.svg",
  CHWS: "sink.svg",
};

export default homeData;
