import { s3assets } from "@/constants";

export const galleryImages = [
  {
    id: "1",
    url: `${s3assets}/assets/gallery/img-1.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 1",
    width: 800, // Replace with actual width
    height: 600, // Replace with actual height
  },
  {
    id: "2",
    url: `${s3assets}/assets/gallery/img-2.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 2",
    width: 800,
    height: 600,
  },
  {
    id: "3",
    url: `${s3assets}/assets/gallery/img-3.webp`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 3",
    width: 800,
    height: 600,
  },
  {
    id: "4",
    url: `${s3assets}/assets/gallery/img-4.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 4",
    width: 800,
    height: 600,
  },
  {
    id: "5",
    url: `${s3assets}/assets/gallery/img-5.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 5",
    width: 800,
    height: 600,
  },
  {
    id: "6",
    url: `${s3assets}/assets/gallery/img-6.jpeg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 6",
    width: 800,
    height: 600,
  },
  {
    id: "7",
    url: `${s3assets}/assets/gallery/img-7.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 7",
    width: 800,
    height: 600,
  },
  {
    id: "8",
    url: `${s3assets}/assets/gallery/img-8.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 8",
    width: 800,
    height: 600,
  },
  {
    id: "9",
    url: `${s3assets}/assets/gallery/img-9.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 9",
    width: 800,
    height: 600,
  },
  {
    id: "10",
    url: `${s3assets}/assets/gallery/img-10.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 10",
    width: 800,
    height: 600,
  },
  {
    id: "11",
    url: `${s3assets}/assets/gallery/img-11.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 11",
    width: 800,
    height: 600,
  },
  {
    id: "12",
    url: `${s3assets}/assets/gallery/img-12.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 12",
    width: 800,
    height: 600,
  },
  {
    id: "13",
    url: `${s3assets}/assets/gallery/img-13.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 13",
    width: 800,
    height: 600,
  },
  {
    id: "14",
    url: `${s3assets}/assets/gallery/img-14.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 14",
    width: 800,
    height: 600,
  },
  {
    id: "15",
    url: `${s3assets}/assets/gallery/img-15.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 15",
    width: 800,
    height: 600,
  },
  {
    id: "16",
    url: `${s3assets}/assets/gallery/img-16.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 16",
    width: 800,
    height: 600,
  },
  {
    id: "17",
    url: `${s3assets}/assets/gallery/img-17.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 17",
    width: 800,
    height: 600,
  },
  {
    id: "18",
    url: `${s3assets}/assets/gallery/img-18.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 18",
    width: 800,
    height: 600,
  },
  {
    id: "19",
    url: `${s3assets}/assets/gallery/img-19.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 19",
    width: 800,
    height: 600,
  },
  {
    id: "20",
    url: `${s3assets}/assets/gallery/img-20.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 20",
    width: 800,
    height: 600,
  },
  {
    id: "21",
    url: `${s3assets}/assets/gallery/img-21.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 21",
    width: 800,
    height: 600,
  },
  {
    id: "22",
    url: `${s3assets}/assets/gallery/img-22.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 22",
    width: 800,
    height: 600,
  },
  {
    id: "23",
    url: `${s3assets}/assets/gallery/img-23.jpg`,
    alt: "FlushJohn Portable Toilet Rental Service - Image 23",
    width: 800,
    height: 600,
  },
];
